{
 "title": "MITRAP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Initial attempt at heatmap",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"mitrap006\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"smps_data\")\n  |> filter(fn: (r) => strings.hasPrefix(v: r._field, prefix: \"nm\"))  \n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"), t: \"_\", u: \".\")) \n  }))\n  |> map(fn: (r) => ({\n      r with nm_bin: float(v: uint(v: r.nm / 10.0)) * 10.0\n  }))\n  //|> aggregateWindow(every: 1m, fn: mean)\n  //|> group(columns: [\"_time\", \"nm_bin\"])\n  |> keep(columns: [\"_time\", \"_value\", \"nm_bin\"])\n  |> yield(name: \"table\")"
    }
   ]
  },
  {
   "title": "Athens - Low Resolution (mitrap006)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "COM1 - VALVE STATE",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 11, "x": 5, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"com1\")\n  |> filter(fn: (r) => r._field == \"valve_state\")\n  |> map(fn: (r) => ({ r with _field: \"Valve State\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"id\"])\n"
    }
   ]
  },
  {
   "title": "COM2 - Flow",
   "type": "timeseries",
   "description": "COM2 from MStack_Flow_Meter",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"mitrap006\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"com2\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "COM1 - RH-T, P",
   "type": "timeseries",
   "description": "COM1 from MStack_Flow_Meter",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"mitrap006\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"com1\")\n    |> filter(fn: (r) => r._field != \"pressure_pa\" and r._field != \"valve_state\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "AE31 - Flow ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ae31\")\n  |> filter(fn: (r) => r._field == \"flow\")\n  |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "AE31 - EBC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 22 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"mitrap006\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ae31\")\n  |> filter(fn: (r) => r._field != \"time_str\" and r._field != \"date_str\" and r._field != \"flow\")\n  |> map(fn: (r) => ({\n      r with _field: strings.replaceAll(v: r._field, t: \"nm\", u: \"\") + \" nanometers\"\n  }))\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "CPC_A20 - Concentration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpc_data\")\n  //|> filter(fn: (r) => r._field != \"total_errors\" and r._field != \"dead_time_us\" and r._field != \"pulse_ratio\" and r._field != \"pulses\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n"
    }
   ]
  }
 ]
}