{
 "title": "MITRAP",
 "time": { "from": "2025-07-28T02:13:43.384Z", "to": "2025-07-28T08:05:32.475Z" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => exists r.installation)\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"installation\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "mpss_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"smps_data\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "com1_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"com1\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "com2_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"com2\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "ae31_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"ae31\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "grimm_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"grimm\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "ma200_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"ma200\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)"
    }
   },
   { "name": "bucket", "query": { "query": "buckets()\n" } }
  ]
 },
 "panels": [
  { "title": "${installation} ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${mpss_name} - Mean hourly concentration per nanometer",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "import \"strings\"\n\nvalve_off_times = from(bucket: \"${bucket}\")\n  |> range(start: time(v: uint(v: v.timeRangeStop) - uint(v: 3600000000000)), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"com1\")\n  |> filter(fn: (r) => r._field == \"valve_state\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r._value == 0)\n  |> keep(columns: [\"_time\"])\n\nall_data = from(bucket: \"${bucket}\")\n  |> range(start: time(v: uint(v: v.timeRangeStop) - uint(v: 3600000000000)), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"smps_data\")\n  |> filter(fn: (r) => strings.hasPrefix(v: r._field, prefix: \"nm\"))\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n\n\njoined = join(\n  tables: {all: all_data, valveOff: valve_off_times},\n  on: [\"_time\"],\n  method: \"inner\"\n)\n\njoined\n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(\n            v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"),\n            t: \"_\", u: \".\"\n          ))\n  }))\n  |> map(fn: (r) => ({ r with hourly_valve_off: r._value }))\n  |> keep(columns: [\"nm\", \"hourly_valve_off\"])\n  |> sort(columns: [\"nm\"])\n"
    },
    {
     "query": "import \"strings\"\n\nvalve_on_times = from(bucket: \"${bucket}\")\n  |> range(start: time(v: uint(v: v.timeRangeStop) - uint(v: 3600000000000)), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"com1\")\n  |> filter(fn: (r) => r._field == \"valve_state\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r._value != 0)\n  |> keep(columns: [\"_time\"])\n\nall_data = from(bucket: \"${bucket}\")\n  |> range(start: time(v: uint(v: v.timeRangeStop) - uint(v: 3600000000000)), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"smps_data\")\n  |> filter(fn: (r) => strings.hasPrefix(v: r._field, prefix: \"nm\"))\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n\n\njoined = join(\n  tables: {all: all_data, valveOn: valve_on_times},\n  on: [\"_time\"],\n  method: \"inner\"\n)\n\njoined\n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(\n            v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"),\n            t: \"_\", u: \".\"\n          ))\n  }))\n  |> map(fn: (r) => ({ r with hourly_valve_on: r._value }))\n  |> keep(columns: [\"nm\", \"hourly_valve_on\"])\n  |> sort(columns: [\"nm\"])\n"
    }
   ]
  },
  {
   "title": "${mpss_name}- Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"smps_data\")\n  |> filter(fn: (r) => strings.hasPrefix(v: r._field, prefix: \"nm\"))  \n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"), t: \"_\", u: \".\")) \n  }))\n  |> map(fn: (r) => ({\n      r with nm_bin: float(v: uint(v: r.nm / 10.0)) * 10.0\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"nm_bin\"])\n  |> yield(name: \"table\")"
    }
   ]
  },
  {
   "title": "${com1_name} - VALVE STATE",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 11, "x": 5, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"com1\")\n  |> filter(fn: (r) => r._field == \"valve_state\")\n  |> map(fn: (r) => ({ r with _field: \"Valve State\" }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"id\"])\n"
    }
   ]
  },
  {
   "title": "${com2_name} - Flow",
   "type": "timeseries",
   "description": "COM2 from MStack_Flow_Meter",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"com2\")\n     |> map(fn: (r) => ({\n      r with\n      _field: if r._field == \"value\" then \"flow\"\n              else r._field\n    }))\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "${com1_name} - RH-T, P",
   "type": "timeseries",
   "description": "COM1 from MStack_Flow_Meter",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"com1\")\n    |> filter(fn: (r) => r._field != \"valve_state\")\n    |> filter(fn: (r) => r._field == \"pressure_kpa\" or r._field == \"c3\" or r._field == \"conc_3_percent\" or r._field == \"conc_c5\" or r._field == \"conc_5_percent\")\n    |> map(fn: (r) => ({\n      r with\n      _field: if r._field == \"c3\" then \"T1\"\n              else if r._field == \"conc_c5\" then \"T2\"\n              else if r._field == \"conc_3_percent\" then \"rh1\"\n              else if r._field == \"conc_5_percent\" then \"rh2\"\n              else if r._field == \"pressure_kpa\" then \"pressure\"\n              else r._field\n    }))\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "${ae31_name} - Flow ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ae31\")\n  |> filter(fn: (r) => r._field == \"flow\")\n  |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "${ae31_name} - EBC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 22 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ae31\")\n  |> filter(fn: (r) => r._field != \"time_str\" and r._field != \"date_str\" and r._field != \"flow\")\n  |> map(fn: (r) => ({\n      r with _field: strings.replaceAll(v: r._field, t: \"nm\", u: \"\") + \" nm\"\n  }))\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "CPC_A20 - Status Error",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpc_data\")\n  |> filter(fn: (r) => r._field == \"status_error\")\n   |> map(fn: (r) => ({\n      r with\n      _field: if r._field == \"status_error\" then \" \"\n              else r._field\n  }))\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "CPC_A20 (VAR) - Liquid Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpc_data\")\n  |> filter(fn: (r) => r._field == \"liquid_level\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "CPC_A20 (VAR) - Concentration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 9, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpc_data\")\n  |> filter(fn: (r) => r._field == \"concentration_cc\" or r._field == \"nozzle_pressure_kPa\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n   |> map(fn: (r) => ({\n      r with\n      _field: if r._field == \"concentration_cc\" then \"concentration\"\n              else if r._field == \"nozzle_pressure_kPa\" then \"nozzle pressure\"\n              else r._field\n  }))\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "${grimm_name} - Hourly Mean per cC",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: time(v: uint(v: v.timeRangeStop) - uint(v: 3600000000000)), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"grimm\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"), t: \"_\", u: \".\")) \n  }))\n  |> group(columns: [\"nm\", \"name\"])\n  |> mean()\n  |> group(columns: [\"_field\", \"name\"])  \n  |> sort(columns: [\"nm\"])"
    }
   ]
  },
  {
   "title": "${grimm_name} - Total Volume",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "query": "import \"math\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"grimm\")\n  //|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"name\"])\n  |> group(columns: [\"_time\", \"name\"]) \n  |> map(fn: (r) => ({\n      r with _value: ((math.pi / 4.0) * r._value ^ 3.0) * (10.0 ^ -9.0)\n  }))\n  |> sum()\n  |> group(columns: [\"name\"]) "
    }
   ]
  },
  {
   "title": "${ma200_name} - Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"ma200\")\n    |> filter(fn: (r) => r._field == \"flow_total\" or r._field == \"flow1\" or r._field == \"flow2\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "${ma200_name} - BCc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"ma200\")\n    |> filter(fn: (r) => r._field == \"uvbcc\" or r._field == \"bluebcc\" or r._field == \"redbcc\" or r._field == \"greenbcc\" or r._field == \"irbcc\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "${ma200_name} - ATN1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"ma200\")\n    |> filter(fn: (r) => r._field == \"uvatn1\" or r._field == \"blueatn1\" or r._field == \"redatn1\" or r._field == \"greenatn1\" or r._field == \"iratn1\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  }
 ]
}