{
 "title": "AQM-HR: Rotterdam - Hoek van Holland (2025)",
 "tags": [
  "AQM",
  "HR",
  "Rotterdam",
  "Port"
 ],
 "time": { "from": "2025-06-30T21:00:00.000Z", "to": "2025-12-08T22:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Station",
    "query": "Rotterdam - Hoek van Holland - HR"
   },
   { "name": "bucket", "query": "pkg002" },
   {
    "name": "interp",
    "label": "Interpolation",
    "query": "None - 192 diameters : mpss , 24 diameters : mpss_24 , 32 diameters : mpss_32 , Piraeus : mpss_006 , Peretola 32 : mpss_p32 "
   }
  ]
 },
 "panels": [
  {
   "title": "Ultrafine Particle Number concentration (#/cm³) ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "agrw = if uint(v: $__interval) < uint(v: 30m) then 30m else $__interval \n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"uf\" and r.installation == \"${Station}\")\n  |> filter(fn: (r) => r._field == \"valve_state\" or r._field == \"concentration_cc\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      r with\n      id: if r.valve_state == 0 then \"Solid\" else if r.valve_state == 1 then \"Ambient\" else \"Invalid\",\n      _value: r.concentration_cc,\n  }))\n  |> filter(fn: (r) => r.id != \"Invalid\")\n  |> group(columns: [\"id\"])\n  |> keep(columns: [\"id\",\"_value\", \"_time\"])\n  |> aggregateWindow(every: agrw, fn: mean, createEmpty: true)\n\n"
    }
   ]
  },
  {
   "title": "Black Carbon mass concentration (µg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"math\"\n\nagrw = if uint(v: $__interval) < uint(v: 15m) then 15m else $__interval \n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ae31\" and r.installation == \"${Station}\" and r._field == \"nm880\")\n//  |> map(fn: (r) => ({\n//      r with _field: strings.replaceAll(v: r._field, t: \"nm\", u: \"\") + \" nm\"\n//  }))\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every:agrw, fn:mean, createEmpty:true)\n  |> map(fn: (r) => ({ r with _value: if r._value>=0 then r._value / 1000.0 else math.NaN() }) )\n"
    }
   ]
  },
  {
   "title": "CO₂ concentration (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"co2\" and r.installation == \"${Station}\" and r._field == \"co2_ppm\")\n    |> filter(fn: (r) => r._value > 50)\n    |> aggregateWindow(every: $__interval, fn:mean)\n    |> keep(columns:[\"_time\",\"_field\",\"freq\",\"_value\"])"
    }
   ]
  },
  {
   "title": "PM2.5 mass concentration (µg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pm\" and r.installation == \"${Station}\")\n  |> filter(fn: (r) => r._field == \"pm25\")\n  |> aggregateWindow(every: $__interval, fn:mean)\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "Size distribution of Ultrafine Particle Number concentration (#/cm³) - Ambient",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"array\"\n\naggrw = if uint(v: $__interval) < uint(v: 2h) then 2h else $__interval \nrangeMs = int(v: v.timeRangeStop) - int(v: v.timeRangeStart)\n\nopts =\n  if rangeMs < 7200000000000 then { // 2h in nanoseconds\n    timeRangeStart: time(v: int(v: v.timeRangeStop) - 7200000000000),\n    timeRangeStop:  v.timeRangeStop\n  }\n  else {\n    timeRangeStart: v.timeRangeStart,\n    timeRangeStop:  v.timeRangeStop\n  }\n\nall_data_0 = from(bucket: \"${bucket}\")\n  |> range(start: opts.timeRangeStart, stop: opts.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${interp}\" and r.installation == \"${Station}\" and r.valve == \"0\")\n  |> keep(columns: [\"_value\",\"_field\",\"_time\"])\n  |> aggregateWindow(every: aggrw, fn: sum, createEmpty: false)\n  \nall_data_1 = from(bucket: \"${bucket}\")\n  |> range(start: opts.timeRangeStart, stop: opts.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${interp}\" and r.installation == \"${Station}\" and r.valve == \"1\")\n  |> keep(columns: [\"_value\",\"_field\",\"_time\"])\n  |> aggregateWindow(every: aggrw, fn: sum, createEmpty: false)\n  \nall_data_1\n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"), t: \"_\", u: \".\")) \n  }))\n  |> map(fn: (r) => ({\n     r with nm_bin: r.nm \n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"nm_bin\"])\n"
    }
   ]
  },
  {
   "title": "Size distribution of Ultrafine Particle Number concentration (#/cm³) - Solid",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"array\"\n\naggrw = if uint(v: $__interval) < uint(v: 2h) then 2h else $__interval \nrangeMs = int(v: v.timeRangeStop) - int(v: v.timeRangeStart)\n\nopts =\n  if rangeMs < 7200000000000 then { // 2h in nanoseconds\n    timeRangeStart: time(v: int(v: v.timeRangeStop) - 7200000000000),\n    timeRangeStop:  v.timeRangeStop\n  }\n  else {\n    timeRangeStart: v.timeRangeStart,\n    timeRangeStop:  v.timeRangeStop\n  }\n\nall_data_0 = from(bucket: \"${bucket}\")\n  |> range(start: opts.timeRangeStart, stop: opts.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${interp}\" and r.installation == \"${Station}\" and r.valve == \"0\")\n  |> keep(columns: [\"_value\",\"_field\",\"_time\"])\n  |> aggregateWindow(every: aggrw, fn: sum, createEmpty: false)\n  \nall_data_1 = from(bucket: \"${bucket}\")\n  |> range(start: opts.timeRangeStart, stop: opts.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${interp}\" and r.installation == \"${Station}\" and r.valve == \"1\")\n  |> keep(columns: [\"_value\",\"_field\",\"_time\"])\n  |> aggregateWindow(every: aggrw, fn: sum, createEmpty: false)\n  \nall_data_0\n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"), t: \"_\", u: \".\")) \n  }))\n  |> map(fn: (r) => ({\n     r with nm_bin: r.nm \n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"nm_bin\"])\n"
    }
   ]
  },
  {
   "title": "Size distribution of Ultrafine Particle Number concentration (#/cm³), over all time range",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"array\"\n\naggrw = if uint(v: $__interval) < uint(v: 2h) then 2h else $__interval \nrangeMs = int(v: v.timeRangeStop) - int(v: v.timeRangeStart)\n\nopts =\n  if rangeMs < 7200000000000 then { // 2h in nanoseconds\n    timeRangeStart: time(v: int(v: v.timeRangeStop) - 7200000000000),\n    timeRangeStop:  v.timeRangeStop\n  }\n  else {\n    timeRangeStart: v.timeRangeStart,\n    timeRangeStop:  v.timeRangeStop\n  }\n\nall_data_0 = from(bucket: \"${bucket}\")\n  |> range(start: opts.timeRangeStart, stop: opts.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${interp}\" and r.installation == \"${Station}\" and r.valve == \"0\")\n  |> keep(columns: [\"_value\",\"_field\",\"_time\"])\n  |> aggregateWindow(every: aggrw, fn: sum, createEmpty: false)\n  \nall_data_1 = from(bucket: \"${bucket}\")\n  |> range(start: opts.timeRangeStart, stop: opts.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${interp}\" and r.installation == \"${Station}\" and r.valve == \"1\")\n  |> keep(columns: [\"_value\",\"_field\",\"_time\"])\n  |> aggregateWindow(every: aggrw, fn: sum, createEmpty: false)\n  \nall_data_1\n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(\n            v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"),\n            t: \"_\", u: \".\"\n          ))\n  }))\n  |> map(fn: (r) => ({ r with hourly_valve_off: r._value }))\n  |> keep(columns: [\"nm\", \"hourly_valve_off\"])\n  |> sort(columns: [\"nm\"])\n"
    },
    {
     "query": "import \"strings\"\nimport \"array\"\n\naggrw = if uint(v: $__interval) < uint(v: 2h) then 2h else $__interval \nrangeMs = int(v: v.timeRangeStop) - int(v: v.timeRangeStart)\n\nopts =\n  if rangeMs < 7200000000000 then { // 2h in nanoseconds\n    timeRangeStart: time(v: int(v: v.timeRangeStop) - 7200000000000),\n    timeRangeStop:  v.timeRangeStop\n  }\n  else {\n    timeRangeStart: v.timeRangeStart,\n    timeRangeStop:  v.timeRangeStop\n  }\n\nall_data_0 = from(bucket: \"${bucket}\")\n  |> range(start: opts.timeRangeStart, stop: opts.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${interp}\" and r.installation == \"${Station}\" and r.valve == \"0\")\n  |> keep(columns: [\"_value\",\"_field\",\"_time\"])\n  |> aggregateWindow(every: aggrw, fn: sum, createEmpty: false)\n  \nall_data_1 = from(bucket: \"${bucket}\")\n  |> range(start: opts.timeRangeStart, stop: opts.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${interp}\" and r.installation == \"${Station}\" and r.valve == \"1\")\n  |> keep(columns: [\"_value\",\"_field\",\"_time\"])\n  |> aggregateWindow(every: aggrw, fn: sum, createEmpty: false)\n\nall_data_0\n  |> map(fn: (r) => ({\n      r with\n      nm: float(v: strings.replaceAll(\n            v: strings.replaceAll(v: r._field, t: \"nm\", u: \"\"),\n            t: \"_\", u: \".\"\n          ))\n  }))\n  |> map(fn: (r) => ({ r with hourly_valve_on: r._value }))\n  |> keep(columns: [\"nm\", \"hourly_valve_on\"])\n  |> sort(columns: [\"nm\"])\n"
    }
   ]
  },
  {
   "title": "CO/NOx/NO₂",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"mitrap006\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"ypen\" and r.installation == \"${Station}\")\n        |> keep(columns: [\"_time\",\"_field\",\"_value\"])\n    |> sort(columns: [\"_time\"])\n"
    }
   ]
  },
  {
   "title": "Organic fraction concentration (μg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "agrw = if uint(v: $__interval) < uint(v: 30m) then 30m else $__interval \n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"org\" and r.installation == \"${Station}\")\n  |> filter(fn: (r) => r._field == \"ppcc\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\"])\n  |> aggregateWindow(every: agrw, fn:mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Elemental concentration (ng/m³)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "query": "agrw = if uint(v: $__interval) < uint(v: 60m) then 60m else $__interval \n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"inorg\" and r.installation == \"${Station}\" and r.calibration == \"0\")\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\n  |> aggregateWindow(every: agrw, fn:mean, createEmpty: true)\n"
    }
   ]
  }
 ]
}