{
 "title": "AQM-CE: Rotterdam - Hoek van Holland (2025)",
 "tags": [
  "AQM",
  "CE",
  "Rotterdam",
  "Port"
 ],
 "time": { "from": "2025-07-22T21:00:00.000Z", "to": "2025-12-08T22:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Station",
    "query": "Rotterdam - Hoek van Holland - CE"
   },
   { "name": "bucket", "query": "pkg002" }
  ]
 },
 "panels": [
  {
   "title": "Ultrafine Particle Number concentration (#/cm³) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "agrw = if uint(v: $__interval) < uint(v: 5m) then 5m else $__interval \n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"uf\" and r.installation == \"${Station}\")\n  |> group(columns:[\"_field\"])\n  |> aggregateWindow(every:agrw, fn:mean, createEmpty:true)\n"
    }
   ]
  },
  {
   "title": "Black Carbon mass concentration (µg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"aeth\" and r.installation == \"${Station}\" and r._field == \"bc6_ug\")\n    |> aggregateWindow(every: $__interval, fn:mean)\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  },
  {
   "title": "CO₂ concentration (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"co2\" and r.installation == \"${Station}\" and r._field == \"value\")\n    |> aggregateWindow(every: $__interval, fn:mean)\n    |> keep(columns:[\"_time\",\"_field\",\"freq\",\"_value\"])"
    }
   ]
  },
  {
   "title": "PM2.5 mass concentration (µg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pm\" and r.installation == \"${Station}\")\n  |> filter(fn: (r) => r._field == \"pm25\")\n  |> aggregateWindow(every: $__interval, fn:mean)\n  |> keep(columns: [\"id\", \"_field\", \"_value\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "CO/NOx/NO₂",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"mitrap006\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"ypen\" and r.installation == \"${Station}\")\n        |> keep(columns: [\"_time\",\"_field\",\"_value\"])\n    |> sort(columns: [\"_time\"])\n"
    }
   ]
  }
 ]
}