{
 "title": "AQM-CE: Air Quality Monitoring, Cost Effective - Athens Aristotelous",
 "time": { "from": "2025-09-13T11:12:51.871Z", "to": "2025-09-14T07:17:32.311Z" },
 "templating": {
  "list": [
   { "name": "AQH_Station", "query": "Athens - Aristotelous - CE" },
   {
    "name": "mpss_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"smps_data\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "com1_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"com1\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "com2_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"com2\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "ae31_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"ae31\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   {
    "name": "grimm_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"grimm\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)\n"
    }
   },
   { "name": "bucket", "query": { "query": "buckets()\n" } },
   {
    "name": "co2_name",
    "query": {
     "query": "from(bucket: \"mitrap006\")\n  |> range(start: -10d)\n  |> filter(fn: (r) => r._measurement == \"co2\" and exists r.instrument)\n  |> keep(columns: [\"instrument\", \"_time\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"instrument\"])\n  |> limit(n:1)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ultrafine Particle Number concentration (#/cm³) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nanodust\" and r.installation == \"${AQH_Station}\")\n  |> filter(fn: (r) => r._field == \"mode\" or r._field == \"pn\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => exists r.mode and exists r.pn)\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.pn),\n        _field: strings.trim(v: r.mode, cutset: \" \\t\\n\")\n  }))\n  |> group(columns: [\"_field\"])\n\n"
    }
   ]
  },
  {
   "title": "CO₂ concentration (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"math\"\n\nwin = 6 + 6\nshiftPrev = 6\npointInterval = 30s\n\nbase =\n  from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"co2\" and r.installation == \"${AQH_Station}\")\n    |> filter(fn: (r) => r._field == \"value\")\n    |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n    |> keep(columns: [\"_time\",\"_value\"])\n    |> sort(columns: [\"_time\"])\n\nrollMean =\n  base\n    |> movingAverage(n: win)\n    |> timeShift(duration: -180s)\n    |> rename(columns: {_value: \"mean_excl\"})\n\nrollE2 =\n  base\n    |> map(fn: (r) => ({ r with _value: r._value*r._value }))\n    |> movingAverage(n: win)\n    |> timeShift(duration: -180s)\n    |> rename(columns: {_value: \"e2_excl\"})\n\njoined1 = join(\n  tables: {o: base, m: rollMean},\n  on: [\"_time\"],\n  method: \"inner\"\n)\n\njoined2 = join(\n    tables: {jm: joined1, e: rollE2},\n    on: [\"_time\"],\n    method: \"inner\"\n)\n\njoined =\n  joined2\n  |> map(fn: (r) => {\n      std = math.sqrt(x: r.e2_excl - r.mean_excl*r.mean_excl)\n      outlier = if math.abs(x: r._value - r.mean_excl) > 3.0*std then true else false\n      return {_time: r._time, _value: r._value, outlier: outlier}\n    })\n    |> filter(fn: (r) => r.outlier == false)\n    |> drop(columns: [\"outlier\"]) \n\njoined\n"
    }
   ]
  },
  {
   "title": "Black Carbon mass concentration (µg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"ma200\" and r.installation == \"${AQH_Station}\")\n    |> filter(fn: (r) => r._field == \"uvbcc\" or r._field == \"bluebcc\" or r._field == \"redbcc\" or r._field == \"greenbcc\" or r._field == \"irbcc\")\n     |> map(fn: (r) => ({\n      r with _value: r._value / 1000.0\n    }))\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )"
    }
   ]
  }
 ]
}